---
title: "Finding stable components of dimensionality reduction"
author: "Hannah Meyer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
devtools::load_all()
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r libraries}
library(ggplot2)
```


# 1. Simulate Data

```{r data simulation, cache=TRUE}
alpha <- c(0, 0.3, 0.5, 0.7, 1)
Y <- lapply(alpha, function(a) {
    simulation <- PhenotypeSimulator::runSimulation(N = 1000, P = 50, tNrSNP = 10000, 
                           SNPfrequencies = c(0.05, 0.1,0.3,0.4), genVar = 0.4,
                           h2s=0.05, h2bg = 0.95, phi = 0.6, seed=a*10,
                           delta=0.4, nonlinear="exp", 
                           proportionNonlinear=a)
    if (a == 0) return(simulation$phenoComponentsFinal$Y)
    if (a != 0) return(simulation$phenoComponentsFinal$Y_transformed)
})
names(Y) <- paste("nonlinear", alpha, sep="")
```

# 2. Run dimensionality reduction

```{r dimensionality reduction, cache=TRUE}
methods <- c( "PCA", "LLE", "LaplacianEigenmap", "ICA")
dr <- lapply(Y, function(y) {
    tmp <- lapply(methods, function(m) {
        subsetDimReduction(Y=y, seed=2+10*alpha, method=m, verbose=TRUE, 
                           nrSubsets = 10, ndim=25)
    })
    names(tmp) <- methods
    return(tmp)
})
saveRDS(dr, "dimReddata.rds")
    ```

# 3. Find stable components

```{r stable components, cache=TRUE}
threshold <- 0.95
stability <- lapply(seq_along(dr), function(a, threshold) {
    nonlinear <- dr[[a]]
    tmp <- lapply(seq_along(nonlinear), function(m) {
        es <- estimateStability(nonlinear[[m]], threshold=threshold,
                                 verbose=TRUE)
        fs <- formatStability(es)
        if(!is.null(fs)) {
            fs$methods <- methods[m]
            fs$alpha <- alpha[a]
        }
        return(fs)
    })
    return(do.call(rbind, tmp))
}, threshold=threshold)

stability <- do.call(rbind, stability)
saveRDS(stability, "stability.rds")
```

# 4. Plot stability
```{r plot stability, fig.show='hold'}
p <- ggplot(stability, aes(x=as.factor(component), y=stability,
                                 fill=as.factor(alpha)))
p + geom_bar(stat = 'identity', position="dodge") +
    facet_grid(as.factor(alpha) ~ methods) +
    scale_fill_manual(
        values=c('#c7e9b4','#7fcdbb','#41b6c4','#1d91c0','#225ea8'),
        name="non-linearity") +
    #ylim(c(0.5,1)) +
    ylab("Stability") +
    xlab("Low dimensional components") +
    theme_bw()
```